[package]
name = "chip_8_rust"
version = "0.1.0"
authors = ["rosborne132"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sdl2 = "0.34.5"
