const SCREEN_WIDTH: u32 = 64;
const SCREEN_HEIGHT: u32 = 32;

const DISPLAY_MODIFIER: u32 = 10;

const DISPLAY_WIDTH: u32 = SCREEN_WIDTH * DISPLAY_MODIFIER;
const DISPLAY_HEIGHT: u32 = SCREEN_HEIGHT * DISPLAY_MODIFIER;
