pub const SCREEN_WIDTH: u32 = 64;
pub const SCREEN_HEIGHT: u32 = 32;

pub const DISPLAY_MODIFIER: u32 = 10;

pub const DISPLAY_WIDTH: u32 = SCREEN_WIDTH * DISPLAY_MODIFIER;
pub const DISPLAY_HEIGHT: u32 = SCREEN_HEIGHT * DISPLAY_MODIFIER;
